_extends: biaw/.github

repository:
  name: website
  description: "The website for Countr"
  homepage: "https://countr.pages.dev"
  private: false
  topics: "website, docusaurus, hacktoberfest"

branches:
  - name: main
    protection:
      required_status_checks:
        checks:
          - context: CodeQL
          - context: ESLint
          - context: DeepScan
          - context: Test Build
