name: Linting

on:
  push:
    branches:
    - production
  pull_request:
    branches:
    - production

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Set up node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
      with:
        node-version: "16.x"

    - name: Set up module cache
      uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
      id: cache-packages
      with:
        path: node_modules
        key: ${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      if: steps.cache-packages.outputs.cache-hit != 'true'

    - name: Run ESLint
      run: npm run lint