name: PR Automation

on:
  pull_request_target:

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest

    steps:
      - name: Automatically label PR
        uses: actions/labeler@2f7477e3004bdfe4bba501d76fae0d81f6eac775 # tag=v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true